extends Node

const OVERWORLD_MAX_X = 64
const OVERWORLD_MAX_Y = 64
const MAX_HEIGHT_LEVELS = 8

const BIOME_COUNT = 4

enum BIOMES {NONE = 0, DESERT = 1, SAVANNAH = 2, ROCKY = 3, GRASSLAND = 4, FOREST = 5}
enum DUNGEON_TILES {ROCK = 0, ROOM = 1, UP_STAIRS = 2, DOWN_STAIRS = 3, FORBIDDEN = 4, DUAL_STAIRS = 5}

enum DIRECTION {SAME, NORTH, EAST, SOUTH, WEST, UP, DOWN}
